### PR TITLE
Switch to debian stretch base image

### PR DESCRIPTION
**Pull request by stefanfoulis**
This to figure out:

- [ ] how should we release this? Do we need a separate release channel and a separate tag name (e.g ``:py3-3.30-stretch``)? Or shall we just make it a regular update on the current release channel.
- [ ] reduce CVEs further (e.g newer version of ImageMagick?)
- [ ] CVE whitelist

### CODE REVIEW

**Comment by glasnt** [comment]
Separate tag for testing, then tag it as the main version? 

Pending full scanning, I think with this upgrade we get dpkg-dev, unsure if that introduces anything more

Is imagemagick a dep of anything, or could we remove it entirely?

**Comment by stefanfoulis** [comment]
release/tagging: yeah. Separate tag for testing and then release as a "regular" version when fully tested sounds like a good idea. Projects should generally work with the upgrade as long as they don't apt-get install any additional packages that don't exist for stretch. And if they don't add custom apt-registries.

imagemagick: As far as I can tell ImageMagick is already pre-installed on the official python image. I'm not sure what the rationale behind that is. Maybe very common python packages like PIL/Pillow depend on it? I don't know.

**Comment by glasnt** [comment]
> Maybe very common python packages like PIL/Pillow depend on it? I don't know.

Pillow doesn't; PIL might have, but PIL is deprecated in favour of Pillow

**Comment by GaretJax** [comment]
It is installed in the buildpack image, which is used by many other projects...

It has just been there since the beginning: https://github.com/docker-library/buildpack-deps/commit/bd9b031a2b416ec8a64f52414ce0b36e41bea2f9

There are use cases for it, but I guess it can just be reinstalled in that case, we just have to make sure that all the default stuff still works.

**Review by glasnt — COMMENTED** [review]
I can't get this out of my "Review Requests" queue without commenting, apparently.

**Comment by GaretJax** [comment]
I'll just close it. I hope life is treating you well @glasnt :-)

**Pull request closed without merging**
